volumes:
  userdb_data:
  orderdb_data:
  inventorydb_data:
version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
  userdb:
    container_name: userbd
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - userdb_data:/var/lib/postgresql/data
    depends_on:
      - zookeeper
      - kafka
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=usersdb
  orderdb:
    container_name: orderdb
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - orderdb_data:/var/lib/postgresql/data
    depends_on:
      - zookeeper
      - kafka
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=orderdb
  inventorydb:
    container_name: inventorydb
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - inventorydb_data:/var/lib/postgresql/data
    depends_on:
      - zookeeper
      - kafka
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=inventorydb
  
