volumes:
  userdb_data:
  orderdb_data:
  inventorydb_data:
version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  # zookeeper1:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - 2182:2182
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2182  
  # zookeeper3:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - 2183:2183
    # environment:
    #   ZOOKEEPER_CLIENT_PORT: 2183
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
    depends_on:
      - zookeeper
  # kafka1:
  #   image: wurstmeister/kafka
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - ./data/kafka1:/var/run/docker.sock
  #   environment:
  #     - KAFKA_ADVERTISED_HOST_NAME=localhost
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2182
  #     - KAFKA_BROKER_ID=2
  #   depends_on:
  #     - zookeeper1
  # kafka2:
  #   image: wurstmeister/kafka
  #   ports:
  #     - 9094:9094
  #   volumes:
  #     - ./data/kafka2:/var/run/docker.sock
  #   environment:
  #     - KAFKA_ADVERTISED_HOST_NAME=localhost
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper3:2183
  #     - KAFKA_BROKER_ID=3
  #   depends_on:
  #     - zookeeper3
  userdb:
    container_name: userbd
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - userdb_data:/var/lib/postgresql/data
    depends_on:
      - zookeeper
      - kafka
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=usersdb
  orderdb:
    container_name: orderdb
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - orderdb_data:/var/lib/postgresql/data
    depends_on:
      - zookeeper
      - kafka
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=orderdb
  inventorydb:
    container_name: inventorydb
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - inventorydb_data:/var/lib/postgresql/data
    depends_on:
      - zookeeper
      - kafka
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=inventorydb
  
